"""a new migration

Revision ID: 021e0c4acebd
Revises: f730aa1c6435
Create Date: 2022-05-19 14:10:23.728403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021e0c4acebd'
down_revision = 'f730aa1c6435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('column', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'column')
    # ### end Alembic commands ###
