"""a new migration

Revision ID: a2d2cd05fd0f
Revises: 32c70dc00c06
Create Date: 2022-05-19 14:15:43.121181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d2cd05fd0f'
down_revision = '32c70dc00c06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('meal', sa.String(length=255), nullable=True))
    op.drop_column('meals', 'cost')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('cost', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('meals', 'meal')
    # ### end Alembic commands ###
