"""a new migration.

Revision ID: c2542b7f6deb
Revises: 8171fd437ba3
Create Date: 2022-05-18 10:09:35.766295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2542b7f6deb'
down_revision = '8171fd437ba3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meals', 'meal_cost',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_meals_meal_cost', table_name='meals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_meals_meal_cost', 'meals', ['meal_cost'], unique=False)
    op.alter_column('meals', 'meal_cost',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
